src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Karma_Exchange_Org_Id__c</fullName>
        <label>Karma Exchange Org Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Karma_Exchange_Org_Secret_Key__c</fullName>
        <label>Karma Exchange Org Secret Key</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/KexOrg.cls
public with sharing virtual class KexOrg {

    // The salesforce org id.
    public String id;

    // A user readable name for the organization.
    public String name;

    // The karma exchange org id.
    public String orgId;
    public String secretKey;

    public KexOrg(Account acc) {
        id = acc.id;
        name = acc.Name;
        orgId = acc.Karma_Exchange_Org_Id__c;
        secretKey = acc.Karma_Exchange_Org_Secret_Key__c;
    }

}