src/objects/GW_Volunteers__Volunteer_Shift__c.object
<CustomObject>
</CustomObject>

src/objects/KexSyncTracker__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Shift__c</fullName>
        <label>Volunteer Shift</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Kex Sync Tracker</label>
    <nameField>
        <displayFormat>SyncEntry-{00000}</displayFormat>
        <label>SyncEntryId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kex Sync Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KexSyncUpcomingShiftsBatch.cls
global without sharing class KexSyncUpcomingShiftsBatch implements Database.Batchable<sObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID FROM GW_Volunteers__Volunteer_Shift__c WHERE GW_Volunteers__Start_Date_Time__c > TODAY ');
    }

    global void execute(Database.BatchableContext BC, List<GW_Volunteers__Volunteer_Shift__c> jobShifts){
        List<KexSyncTracker__c> shiftList = new List<KexSyncTracker__c>();
        for (GW_Volunteers__Volunteer_Shift__c shift : jobShifts) {
            KexSyncTracker__c sync = new KexSyncTracker__c();
            sync.Volunteer_Shift__c = shift.Id;
            shiftList.add(sync);
        }
        insert shiftList;
    }

    global void finish(Database.BatchableContext BC) {
        // Both volunteer contacts and shifts need to be synced.

        Database.Batchable<sObject> syncShiftsJob =
            new KexCompactAndSyncPendingShiftsBatch();

        // We sync the contacts prior to syncing the shifts. We want all preferences
        // copied over if the user doesn't already exist.
        database.executebatch(
            new KexSyncVolunteerContactsBatch(syncShiftsJob));
    }
}