src/objects/GW_Volunteers__Volunteer_Shift__c.object
<CustomObject>
</CustomObject>

src/objects/Karma_Exchange_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Auto_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enables automatically syncing volunteer job info with Karma Exchange.</description>
        <label>Auto Sync</label>
        <type>Checkbox</type>
    </fields>
    <label>Karma Exchange Settings</label>
</CustomObject>

src/objects/KexSyncTracker__c.object
<CustomObject>
    <fields>
        <fullName>Volunteer_Job__c</fullName>
        <label>Volunteer Job</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Kex Sync Tracker</label>
    <nameField>
        <displayFormat>SyncEntry-{00000}</displayFormat>
        <label>SyncEntryId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Kex Sync Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/KexSyncContactTest.cls
@IsTest
private class KexSyncContactTest {

    static testmethod void testSyncContact() {
        KexTestDataFactory testDataFactory = new KexTestDataFactory();
        GW_Volunteers__Volunteer_Shift__c shift =
            testDataFactory.createShift();
        Contact volunteer =
            testDataFactory.createContact();
        testDataFactory.registerVolunteer(shift, volunteer);

        // Validate no updates pending
        List<KexSyncTracker__c> pendingContacts =
            [SELECT Id,Volunteer_Job__c FROM KexSyncTracker__c  where Volunteer_Contact__c != null];
        System.assert(pendingContacts.size() == 0, 'Pending contacts size mismatch: ' + pendingContacts);

        // Update FirstName
        volunteer.FirstName =
            volunteer.FirstName + '2';
        update volunteer;

        pendingContacts =
            [SELECT Id,Volunteer_Job__c FROM KexSyncTracker__c  where Volunteer_Contact__c != null];
        System.assert(pendingContacts.size() == 1, 'Pending contacts size mismatch: ' + pendingContacts);

        // Update LastName
        volunteer.LastName =
            volunteer.LastName + '2';
        update volunteer;

        pendingContacts =
            [SELECT Id,Volunteer_Job__c FROM KexSyncTracker__c  where Volunteer_Contact__c != null];
        System.assert(pendingContacts.size() == 2, 'Pending contacts size mismatch: ' + pendingContacts);

        // Update Email
        volunteer.Email =
            'new.' + volunteer.Email;
        update volunteer;

        pendingContacts =
            [SELECT Id,Volunteer_Job__c FROM KexSyncTracker__c  where Volunteer_Contact__c != null];
        System.assert(pendingContacts.size() == 3, 'Pending contacts size mismatch: ' + pendingContacts);

        // Update opt out pref
        volunteer.HasOptedOutOfEmail =
            !volunteer.HasOptedOutOfEmail;
        update volunteer;

        pendingContacts =
            [SELECT Id,Volunteer_Job__c FROM KexSyncTracker__c  where Volunteer_Contact__c != null];
        System.assert(pendingContacts.size() == 4, 'Pending contacts size mismatch: ' + pendingContacts);

        // Disable auto update and ensure that we don't add rows.
        Karma_Exchange_Settings__c adminSettings =
            Karma_Exchange_Settings__c.getInstance();
        adminSettings.Auto_Sync__c = false;
        upsert adminSettings;

        volunteer.Email =
            'new.' + volunteer.Email;
        update volunteer;

        pendingContacts =
            [SELECT Id,Volunteer_Job__c FROM KexSyncTracker__c  where Volunteer_Contact__c != null];
        System.assert(pendingContacts.size() == 4, 'Pending contacts size mismatch: ' + pendingContacts);
    }

}